spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:crowdpulse;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;NON_KEYWORDS=USER
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Exclude Redis AutoConfiguration so it does not connect to external Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
management.health.redis.enabled=false

# Actuator Endpoints
management.endpoints.web.exposure.include=*

# Prometheus Metrics
management.prometheus.metrics.export.enabled=true

# Health Details
management.endpoint.health.show-details=always

management.endpoint.prometheus.access=unrestricted
management.endpoint.metrics.access=unrestricted
management.endpoint.health.access=unrestricted