-- Insert places
INSERT INTO places (id, name, description, type, city, state, country, latitude, longitude, radius, capacity, is_active, scaling_factor, admin_offset, base_throughput, peak_start, peak_end, peak_multiplier, season_multiplier, max_daily_capacity, concurrent_capacity, queue_status) VALUES 
(1, 'Kedarnath Temple', 'Ancient Jyotirlinga high in the Himalayas', 'QUEUE', 'Rudraprayag', 'Uttarakhand', 'India', 30.7352, 79.0669, 500, 2000, true, 1.5, 100, 35, '08:00', '12:00', 2.0, 1.8, 13000, 2000, 'ACTIVE'),
(2, 'Marine Drive', 'Iconic sea-facing curved boulevard known as the Queen''s Necklace', 'VIBE', 'Mumbai', 'Maharashtra', 'India', 18.943, 72.8238, 1000, 5000, true, 1.2, 0, 45, '17:00', '21:00', 1.5, 1.0, 50000, 5000, 'ACTIVE'),
(3, 'Taj Mahal', 'World Heritage ivory-white marble mausoleum on the Yamuna river', 'TIMED', 'Agra', 'Uttar Pradesh', 'India', 27.1751, 78.0421, 800, 3000, true, 1.2, 0, 40, '09:00', '14:00', 1.8, 1.2, 35000, 3000, 'ACTIVE'),
(4, 'Kashi Vishwanath', 'Sacred Jyotirlinga temple on the western bank of the holy Ganges', 'QUEUE', 'Varanasi', 'Uttar Pradesh', 'India', 25.310853, 83.010678, 700, 5000, true, 1.2, 0, 50, '09:00', '16:00', 2.5, 2.0, 800000, 3000, 'ACTIVE'),
(5, 'Vaishno Devi Temple', 'Sacred cave shrine of Goddess Vaishno Devi in Trikuta mountains', 'QUEUE', 'Katra', 'Jammu and Kashmir', 'India', 33.0299, 74.9482, 500, 10000, true, 1.2, 0, 45, '08:00', '18:00', 2.5, 1.5, 50000, 5000, 'ACTIVE');

-- Insert place_details
INSERT INTO place_details (id, place_id, description, significance, best_time, peak_months, off_peak_months, daily_timings, rituals, reach_info, images, tags, avg_daily_footfall, festival_rush_multiplier, queue_config) VALUES
(1, 1, 'An ancient Hindu temple dedicated to Lord Shiva, situated at an altitude of 3,583 meters in the Garhwal Himalayan range.', 'One of the twelve Jyotirlingas and a vital part of the Char Dham Yatra, symbolizing spiritual liberation.', 'May to June or September to October to avoid extreme weather and monsoon risks.', '["May", "June"]', '["July", "August", "November"]', '{"open": "04:00", "close": "21:00", "aartiTimings": ["04:00", "18:30"]}', '[{"name": "Maha Abhishek", "time": "04:00", "description": "The morning ritual involving the ritual bathing of the Shiva Lingam."}, {"name": "Sandhya Aarti", "time": "18:30", "description": "Evening devotional lamp ceremony performed in praise of Lord Shiva."}]', '{"byAir": "Nearest airport is Jolly Grant Airport, Dehradun (238 km).", "byRoad": "Road connectivity up to Sonprayag/Gaurikund.", "byTrain": "Nearest railway station is Rishikesh (216 km).", "trekInfo": "16 km trek from Gaurikund, taking approximately 6-8 hours depending on physical fitness."}', '["/kedarnath.jpg"]', '["spiritual", "temple", "trek", "himalayas", "jyotirlinga"]', 15000, 2.5, '{"avgGroupSize": 2, "throughputPerMinute": 25}'),
(2, 2, 'Marine Drive is a 3.6-kilometre-long boulevard along the Netaji Subhash Chandra Bose Road in South Mumbai, famous for its sweeping panoramic view of the Arabian Sea.', 'Known as the Queen''s Necklace for the nocturnal streetlights that resemble pearls. Part of UNESCO Victorian and Art Deco Ensembles of Mumbai.', 'Evenings (5:00 PM - 8:30 PM) for sunset views and cool sea breeze.', '["November", "December", "January", "February"]', '["June", "July", "August"]', '{"open": "Open 24 Hours", "close": "Open 24 Hours"}', '[{"name": "Sunset Viewing", "time": "18:00", "description": "Gathering along the promenade to watch the sunset over the Arabian Sea."}, {"name": "Queen''s Necklace Illumination", "time": "19:00", "description": "Iconic boulevard streetlights illuminate in a golden crescent."}]', '{"byAir": "Chhatrapati Shivaji Maharaj International Airport (22 km).", "byRail": "Churchgate (Western Line) & Marine Lines railway stations within walking distance.", "byRoad": "Well connected via Eastern Freeway, Marine Lines Flyover, and Coastal Road."}', '["/marine_drive.jpg"]', '["promenade", "mumbai", "sunset", "coastal", "heritage"]', 45000, 2.0, '{"mode": "Open Promenade", "liveMonitoring": true, "communityEnabled": true}'),
(3, 3, 'An ivory-white marble mausoleum on the south bank of the Yamuna river in Agra, commissioned in 1632 by the Mughal emperor Shah Jahan.', 'A UNESCO World Heritage Site and one of the New 7 Wonders of the World, representing eternal love and Mughal architecture.', 'Sunrise (6:00 AM - 8:00 AM) for minimal crowds and ethereal morning light, or winter months (Oct to Mar).', '["October", "November", "December", "January", "February"]', '["May", "June", "July"]', '{"open": "06:00", "close": "18:30"}', '[{"name": "Sunrise Viewing", "time": "06:00", "description": "Spectacular sunrise lighting over the white marble dome."}, {"name": "Sunset Viewing", "time": "17:30", "description": "Golden hour glow across the reflecting pools and Mughal gardens."}]', '{"byAir": "Agra Airport Kheria (12 km) or Delhi IGI Airport (220 km via Yamuna Expressway).", "byRail": "Agra Cantt Railway Station (6 km) served by Gatimaan & Vande Bharat Express.", "byRoad": "Direct access via Yamuna Expressway from Delhi/NCR (approx. 2.5 hours)." }', '["/taj_mahal.jpg"]', '["wonder", "unesco", "heritage", "monument", "agra", "marble"]', 35000, 2.5, '{"mode": "Timed Slots", "liveMonitoring": true, "communityEnabled": true}'),
(4, 4, 'Kashi Vishwanath is one of the holiest Shiva temples in India and among the twelve Jyotirlingas. It receives massive daily pilgrimage traffic throughout the year.', 'One of the most sacred temples dedicated to Lord Shiva on the sacred Ganges river.', 'Early Morning (4 AM - 7 AM)', '["Shravan", "Mahashivratri", "Dev Deepawali"]', '["July", "August"]', '{"open": "04:00", "close": "23:00"}', '[{"name": "Mangala Aarti", "time": "03:00"}, {"name": "Bhog Aarti", "time": "11:15"}, {"name": "Sandhya Aarti", "time": "19:00"}, {"name": "Shringar Aarti", "time": "21:00"}]', '{"byAir": "Lal Bahadur Shastri International Airport (26 km). Taxis and buses available to temple corridor.", "byRail": "Varanasi Junction and Banaras stations connected to all major Indian cities.", "byRoad": "Accessible via NH-19. Electric shuttle and walking corridor available near temple."}', '["/kashi-vishwanath.webp"]', '["Shiva", "Jyotirlinga", "Varanasi", "Temple", "Pilgrimage"]', 150000, 4.0, '{"mode": "Hybrid Virtual Queue", "liveMonitoring": true, "communityEnabled": true}'),
(5, 5, 'Sacred cave shrine of Goddess Vaishno Devi in Trikuta mountains, 12km uphill trek from Katra base camp.', 'One of India''s most visited pilgrimage sites, fulfills wishes of devotees.', 'Summer (Mar-Jun) for pleasant weather, avoid peak Navratri.', '["March", "April", "September", "October", "November"]', '["January", "February", "July", "August"]', '{"open": "04:00", "close": "23:00"}', '[{"name": "Shringar Aarti", "time": "07:30"}, {"name": "Havan Aarti", "time": "12:00"}, {"name": "Sandhya Aarti", "time": "19:00"}]', '{"byAir": "Jammu Airport (45km), helicopters available from Katra helipad.", "byRail": "Shri Mata Vaishno Devi Katra Railway Station (SVDK).", "byRoad": "Jammu-Katra highway, direct express buses from Delhi, Chandigarh, and Jammu."}', '["/vaishno_devi.jpg"]', '["pilgrimage", "temple", "trek", "navratri", "shrine"]', 26000, 4.0, '{"mode": "RFID_Parchi", "liveMonitoring": true, "communityEnabled": true}');

-- Insert sample community updates
INSERT INTO community_updates (id, place_id, reported_queue_length, throughput_per_min, queue_status, note, created_at) VALUES
(1, 1, 150, 25, 'ACTIVE', 'Smooth darshan movement near main sanctum.', CURRENT_TIMESTAMP),
(2, 2, 90, 45, 'ACTIVE', 'Pleasant breeze, gentle evening crowd on promenade.', CURRENT_TIMESTAMP),
(3, 3, 210, 35, 'ACTIVE', 'Moderate queue through East and West security gates.', CURRENT_TIMESTAMP),
(4, 4, 300, 50, 'ACTIVE', 'Steady crowd movement through VIP and general corridors.', CURRENT_TIMESTAMP),
(5, 5, 200, 40, 'ACTIVE', 'Clear queue movement at Bhavan.', CURRENT_TIMESTAMP);

-- Insert sample queue metrics for hourly analytics & charts
INSERT INTO queue_metrics (id, place_id, timestamp, active_users, shadow_users, total_people, corrected_people, throughput, wait_time, efficiency_factor) VALUES
(1, 1, CURRENT_TIMESTAMP, 15, 10, 80, 95, 25.0, 18, 0.35),
(2, 2, CURRENT_TIMESTAMP, 30, 10, 120, 140, 45.0, 10, 0.45),
(3, 3, CURRENT_TIMESTAMP, 40, 15, 200, 240, 35.0, 25, 0.35),
(4, 4, CURRENT_TIMESTAMP, 40, 20, 250, 300, 45.0, 30, 0.35),
(5, 5, CURRENT_TIMESTAMP, 25, 15, 180, 220, 35.0, 22, 0.35);

