-- Insert places
INSERT INTO places (id, name, description, type, city, state, country, latitude, longitude, radius, capacity, is_active, scaling_factor, admin_offset, base_throughput, peak_start, peak_end, peak_multiplier, season_multiplier, max_daily_capacity, concurrent_capacity, queue_status) VALUES 
(1, 'Kedarnath Temple', NULL, 'QUEUE', 'Rudraprayag', 'Uttarakhand', 'India', 30.7352, 79.0669, 500, 2000, true, 1.5, 100, 35, '08:00', '12:00', 2.0, 1.8, 13000, 2000, 'ACTIVE'),
(2, 'Marine Drive', NULL, 'VIBE', 'Mumbai', 'Maharashtra', 'India', 18.943, 72.8238, 1000, 5000, true, 1.2, 0, 30, NULL, NULL, 1.5, 1.0, 13000, 2000, 'ACTIVE'),
(3, 'Taj Mahal', NULL, 'TIMED', 'Agra', 'Uttar Pradesh', 'India', 27.1751, 78.0421, 800, 3000, true, 1.2, 0, 30, NULL, NULL, 1.5, 1.0, 13000, 2000, 'ACTIVE'),
(4, 'Kashi Vishwanath', NULL, 'QUEUE', 'Varanasi', 'Uttar Pradesh', 'India', 25.310853, 83.010678, 700, 5000, true, 1.2, 0, 2000, '09:00:00', '16:00:00', 2.5, 4.0, 800000, 3000, 'ACTIVE'),
(5, 'Vaishno Devi Temple', 'Sacred cave shrine of Goddess Vaishno Devi in Trikuta mountains.', 'QUEUE', 'Katra', 'Jammu and Kashmir', 'India', 33.0299, 74.9482, 500, 10000, true, 1.2, 0, 3000, '08:00', '18:00', 2.5, 1.5, 50000, 5000, 'ACTIVE');

-- Insert place_details
INSERT INTO place_details (id, place_id, description, significance, best_time, peak_months, off_peak_months, daily_timings, rituals, reach_info, images, tags, avg_daily_footfall, festival_rush_multiplier, queue_config) VALUES
(1, 1, 'An ancient Hindu temple dedicated to Lord Shiva, situated at an altitude of 3,583 meters in the Garhwal Himalayan range.', 'One of the twelve Jyotirlingas and a vital part of the Char Dham Yatra, symbolizing spiritual liberation.', 'May to June or September to October to avoid extreme weather and monsoon risks.', '["May", "June"]', '["July", "August", "November"]', '{"open": "04:00", "close": "21:00", "aartiTimings": ["04:00", "18:30"]}', '[{"name": "Maha Abhishek", "time": "04:00", "description": "The morning ritual involving the ritual bathing of the Shiva Lingam."}, {"name": "Sandhya Aarti", "time": "18:30", "description": "Evening devotional lamp ceremony performed in praise of Lord Shiva."}]', '{"byAir": "Nearest airport is Jolly Grant Airport, Dehradun.", "byRoad": "Road connectivity up to Sonprayag/Gaurikund.", "byTrain": "Nearest railway station is Rishikesh.", "trekInfo": "16 km trek from Gaurikund, taking approximately 6-8 hours depending on physical fitness."}', '["https://upload.wikimedia.org/wikipedia/commons/4/4b/Kedarnath_Temple_1.jpg", "https://upload.wikimedia.org/wikipedia/commons/c/c5/Kedarnath_Temple_Uttarakhand.jpg", "https://images.unsplash.com/photo-1626082897645-316260840484"]', '["spiritual", "temple", "trek", "himalayas"]', 15000, 2.5, '{"avgGroupSize": 2, "throughputPerMinute": 25}'),
(2, 4, 'Kashi Vishwanath is one of the holiest Shiva temples in India and among the twelve Jyotirlingas. It receives massive daily pilgrimage traffic throughout the year.', 'One of the most sacred temples dedicated to Lord Shiva.', 'Early Morning (4 AM - 7 AM)', '["Shravan", "Mahashivratri", "Dev Deepawali"]', '["July", "August"]', '{"open": "04:00 AM", "close": "11:00 PM"}', '[{"name": "Mangala Aarti", "time": "03:00 AM"}, {"name": "Bhog Aarti", "time": "11:15 AM"}, {"name": "Sandhya Aarti", "time": "07:00 PM"}, {"name": "Shringar Aarti", "time": "09:00 PM"}]', '{"byAir": "Lal Bahadur Shastri International Airport (26 km). Taxis and buses available to temple corridor.", "byRail": "Varanasi Junction and Manduadih stations connected to all major Indian cities.", "byRoad": "Accessible via NH-19. Electric shuttle and walking corridor available near temple."}', '["https://upload.wikimedia.org/wikipedia/commons/3/3f/Kashi_Vishwanath.jpg"]', '["Shiva", "Jyotirlinga", "Varanasi", "Temple", "Pilgrimage"]', 150000, 4.0, '{"mode": "Hybrid Virtual Queue", "liveMonitoring": true, "communityEnabled": true}'),
(3, 5, 'Sacred cave shrine of Goddess Vaishno Devi in Trikuta mountains, 12km uphill trek from Katra base camp.', 'One of India''s most visited pilgrimage sites, fulfills wishes of devotees.', 'Summer (Mar-Jun) for pleasant weather, avoid peak Navratri.', '["March", "April", "September", "October", "November"]', '["January", "February", "July", "August"]', '{"open": "04:00", "close": "23:00"}', '[{"name": "Shringar Aarti", "time": "07:30"}, {"name": "Havan Aarti", "time": "12:00"}, {"name": "Sandhya Aarti", "time": "19:00"}]', '{"byAir": "Jammu Airport (45km), helicopters from Katra helipad", "byRail": "Udhampur or Katra Railway Station", "byRoad": "Jammu-Katra highway, taxis/buses from Jammu (50km)"}', '["https://upload.wikimedia.org/wikipedia/commons/7/70/Vaishno_Devi_Bhavan.jpg"]', '["pilgrimage", "temple", "trek", "navratri", "shrine"]', 26000, 4.0, '{"mode": "RFID_Parchi", "liveMonitoring": true, "communityEnabled": true}');

-- Insert sample community update
INSERT INTO community_updates (id, place_id, reported_queue_length, throughput_per_min, queue_status, note, created_at) VALUES
(1, 1, 150, 25, 'ACTIVE', 'Smooth darshan movement near main sanctum.', CURRENT_TIMESTAMP),
(2, 4, 300, 50, 'ACTIVE', 'Steady crowd movement through VIP and general gates.', CURRENT_TIMESTAMP),
(3, 5, 200, 40, 'ACTIVE', 'Clear queue movement at Bhavan.', CURRENT_TIMESTAMP);

-- Insert sample queue metrics for analytics
INSERT INTO queue_metrics (id, place_id, timestamp, active_users, shadow_users, total_people, corrected_people, throughput, wait_time, efficiency_factor) VALUES
(1, 1, CURRENT_TIMESTAMP, 15, 10, 80, 95, 25.0, 18, 0.35),
(2, 4, CURRENT_TIMESTAMP, 40, 20, 250, 300, 45.0, 30, 0.35),
(3, 5, CURRENT_TIMESTAMP, 25, 15, 180, 220, 35.0, 22, 0.35);

